/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeasonalHouseRouteImport } from './routes/seasonal-house'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BeginTheJourneyRouteImport } from './routes/begin-the-journey'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioWorkWithMeRouteImport } from './routes/studio/work-with-me'
import { Route as StudioWhySeasonalRouteImport } from './routes/studio/why-seasonal'
import { Route as StudioVintageNotesRouteImport } from './routes/studio/vintage-notes'
import { Route as StudioUnlockMoreRouteImport } from './routes/studio/unlock-more'
import { Route as StudioSoftRoomRouteImport } from './routes/studio/soft-room'
import { Route as StudioSeasonalWeatherRouteImport } from './routes/studio/seasonal-weather'
import { Route as StudioPositioningRouteImport } from './routes/studio/positioning'
import { Route as StudioPortfolioRouteImport } from './routes/studio/portfolio'
import { Route as StudioMorningRoomRouteImport } from './routes/studio/morning-room'
import { Route as StudioMoodboardRouteImport } from './routes/studio/moodboard'
import { Route as StudioManifestoRouteImport } from './routes/studio/manifesto'
import { Route as StudioLicencingRouteImport } from './routes/studio/licencing'
import { Route as StudioJournalRouteImport } from './routes/studio/journal'
import { Route as StudioInteriorsRouteImport } from './routes/studio/interiors'
import { Route as StudioHomewareRouteImport } from './routes/studio/homeware'
import { Route as StudioGardenRouteImport } from './routes/studio/garden'
import { Route as StudioEveningLoungeRouteImport } from './routes/studio/evening-lounge'
import { Route as StudioDepthLevelsRouteImport } from './routes/studio/depth-levels'
import { Route as StudioDemoRouteImport } from './routes/studio/demo'
import { Route as StudioCollectionsRouteImport } from './routes/studio/collections'
import { Route as StudioAnotherRoomRouteImport } from './routes/studio/another-room'
import { Route as StudioAboutRouteImport } from './routes/studio/about'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as ApiWeatherRouteImport } from './routes/api.weather'

const SeasonalHouseRoute = SeasonalHouseRouteImport.update({
  id: '/seasonal-house',
  path: '/seasonal-house',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginTheJourneyRoute = BeginTheJourneyRouteImport.update({
  id: '/begin-the-journey',
  path: '/begin-the-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioWorkWithMeRoute = StudioWorkWithMeRouteImport.update({
  id: '/studio/work-with-me',
  path: '/studio/work-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioWhySeasonalRoute = StudioWhySeasonalRouteImport.update({
  id: '/studio/why-seasonal',
  path: '/studio/why-seasonal',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioVintageNotesRoute = StudioVintageNotesRouteImport.update({
  id: '/studio/vintage-notes',
  path: '/studio/vintage-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioUnlockMoreRoute = StudioUnlockMoreRouteImport.update({
  id: '/studio/unlock-more',
  path: '/studio/unlock-more',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSoftRoomRoute = StudioSoftRoomRouteImport.update({
  id: '/studio/soft-room',
  path: '/studio/soft-room',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSeasonalWeatherRoute = StudioSeasonalWeatherRouteImport.update({
  id: '/studio/seasonal-weather',
  path: '/studio/seasonal-weather',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPositioningRoute = StudioPositioningRouteImport.update({
  id: '/studio/positioning',
  path: '/studio/positioning',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPortfolioRoute = StudioPortfolioRouteImport.update({
  id: '/studio/portfolio',
  path: '/studio/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioMorningRoomRoute = StudioMorningRoomRouteImport.update({
  id: '/studio/morning-room',
  path: '/studio/morning-room',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioMoodboardRoute = StudioMoodboardRouteImport.update({
  id: '/studio/moodboard',
  path: '/studio/moodboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioManifestoRoute = StudioManifestoRouteImport.update({
  id: '/studio/manifesto',
  path: '/studio/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioLicencingRoute = StudioLicencingRouteImport.update({
  id: '/studio/licencing',
  path: '/studio/licencing',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioJournalRoute = StudioJournalRouteImport.update({
  id: '/studio/journal',
  path: '/studio/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioInteriorsRoute = StudioInteriorsRouteImport.update({
  id: '/studio/interiors',
  path: '/studio/interiors',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioHomewareRoute = StudioHomewareRouteImport.update({
  id: '/studio/homeware',
  path: '/studio/homeware',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioGardenRoute = StudioGardenRouteImport.update({
  id: '/studio/garden',
  path: '/studio/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioEveningLoungeRoute = StudioEveningLoungeRouteImport.update({
  id: '/studio/evening-lounge',
  path: '/studio/evening-lounge',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioDepthLevelsRoute = StudioDepthLevelsRouteImport.update({
  id: '/studio/depth-levels',
  path: '/studio/depth-levels',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioDemoRoute = StudioDemoRouteImport.update({
  id: '/studio/demo',
  path: '/studio/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioCollectionsRoute = StudioCollectionsRouteImport.update({
  id: '/studio/collections',
  path: '/studio/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAnotherRoomRoute = StudioAnotherRoomRouteImport.update({
  id: '/studio/another-room',
  path: '/studio/another-room',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAboutRoute = StudioAboutRouteImport.update({
  id: '/studio/about',
  path: '/studio/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/begin-the-journey': typeof BeginTheJourneyRoute
  '/explore': typeof ExploreRoute
  '/seasonal-house': typeof SeasonalHouseRoute
  '/api/weather': typeof ApiWeatherRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/studio/about': typeof StudioAboutRoute
  '/studio/another-room': typeof StudioAnotherRoomRoute
  '/studio/collections': typeof StudioCollectionsRoute
  '/studio/demo': typeof StudioDemoRoute
  '/studio/depth-levels': typeof StudioDepthLevelsRoute
  '/studio/evening-lounge': typeof StudioEveningLoungeRoute
  '/studio/garden': typeof StudioGardenRoute
  '/studio/homeware': typeof StudioHomewareRoute
  '/studio/interiors': typeof StudioInteriorsRoute
  '/studio/journal': typeof StudioJournalRoute
  '/studio/licencing': typeof StudioLicencingRoute
  '/studio/manifesto': typeof StudioManifestoRoute
  '/studio/moodboard': typeof StudioMoodboardRoute
  '/studio/morning-room': typeof StudioMorningRoomRoute
  '/studio/portfolio': typeof StudioPortfolioRoute
  '/studio/positioning': typeof StudioPositioningRoute
  '/studio/seasonal-weather': typeof StudioSeasonalWeatherRoute
  '/studio/soft-room': typeof StudioSoftRoomRoute
  '/studio/unlock-more': typeof StudioUnlockMoreRoute
  '/studio/vintage-notes': typeof StudioVintageNotesRoute
  '/studio/why-seasonal': typeof StudioWhySeasonalRoute
  '/studio/work-with-me': typeof StudioWorkWithMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/begin-the-journey': typeof BeginTheJourneyRoute
  '/explore': typeof ExploreRoute
  '/seasonal-house': typeof SeasonalHouseRoute
  '/api/weather': typeof ApiWeatherRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/studio/about': typeof StudioAboutRoute
  '/studio/another-room': typeof StudioAnotherRoomRoute
  '/studio/collections': typeof StudioCollectionsRoute
  '/studio/demo': typeof StudioDemoRoute
  '/studio/depth-levels': typeof StudioDepthLevelsRoute
  '/studio/evening-lounge': typeof StudioEveningLoungeRoute
  '/studio/garden': typeof StudioGardenRoute
  '/studio/homeware': typeof StudioHomewareRoute
  '/studio/interiors': typeof StudioInteriorsRoute
  '/studio/journal': typeof StudioJournalRoute
  '/studio/licencing': typeof StudioLicencingRoute
  '/studio/manifesto': typeof StudioManifestoRoute
  '/studio/moodboard': typeof StudioMoodboardRoute
  '/studio/morning-room': typeof StudioMorningRoomRoute
  '/studio/portfolio': typeof StudioPortfolioRoute
  '/studio/positioning': typeof StudioPositioningRoute
  '/studio/seasonal-weather': typeof StudioSeasonalWeatherRoute
  '/studio/soft-room': typeof StudioSoftRoomRoute
  '/studio/unlock-more': typeof StudioUnlockMoreRoute
  '/studio/vintage-notes': typeof StudioVintageNotesRoute
  '/studio/why-seasonal': typeof StudioWhySeasonalRoute
  '/studio/work-with-me': typeof StudioWorkWithMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/begin-the-journey': typeof BeginTheJourneyRoute
  '/explore': typeof ExploreRoute
  '/seasonal-house': typeof SeasonalHouseRoute
  '/api/weather': typeof ApiWeatherRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/studio/about': typeof StudioAboutRoute
  '/studio/another-room': typeof StudioAnotherRoomRoute
  '/studio/collections': typeof StudioCollectionsRoute
  '/studio/demo': typeof StudioDemoRoute
  '/studio/depth-levels': typeof StudioDepthLevelsRoute
  '/studio/evening-lounge': typeof StudioEveningLoungeRoute
  '/studio/garden': typeof StudioGardenRoute
  '/studio/homeware': typeof StudioHomewareRoute
  '/studio/interiors': typeof StudioInteriorsRoute
  '/studio/journal': typeof StudioJournalRoute
  '/studio/licencing': typeof StudioLicencingRoute
  '/studio/manifesto': typeof StudioManifestoRoute
  '/studio/moodboard': typeof StudioMoodboardRoute
  '/studio/morning-room': typeof StudioMorningRoomRoute
  '/studio/portfolio': typeof StudioPortfolioRoute
  '/studio/positioning': typeof StudioPositioningRoute
  '/studio/seasonal-weather': typeof StudioSeasonalWeatherRoute
  '/studio/soft-room': typeof StudioSoftRoomRoute
  '/studio/unlock-more': typeof StudioUnlockMoreRoute
  '/studio/vintage-notes': typeof StudioVintageNotesRoute
  '/studio/why-seasonal': typeof StudioWhySeasonalRoute
  '/studio/work-with-me': typeof StudioWorkWithMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/begin-the-journey'
    | '/explore'
    | '/seasonal-house'
    | '/api/weather'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/products/$productId'
    | '/studio/about'
    | '/studio/another-room'
    | '/studio/collections'
    | '/studio/demo'
    | '/studio/depth-levels'
    | '/studio/evening-lounge'
    | '/studio/garden'
    | '/studio/homeware'
    | '/studio/interiors'
    | '/studio/journal'
    | '/studio/licencing'
    | '/studio/manifesto'
    | '/studio/moodboard'
    | '/studio/morning-room'
    | '/studio/portfolio'
    | '/studio/positioning'
    | '/studio/seasonal-weather'
    | '/studio/soft-room'
    | '/studio/unlock-more'
    | '/studio/vintage-notes'
    | '/studio/why-seasonal'
    | '/studio/work-with-me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/begin-the-journey'
    | '/explore'
    | '/seasonal-house'
    | '/api/weather'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/products/$productId'
    | '/studio/about'
    | '/studio/another-room'
    | '/studio/collections'
    | '/studio/demo'
    | '/studio/depth-levels'
    | '/studio/evening-lounge'
    | '/studio/garden'
    | '/studio/homeware'
    | '/studio/interiors'
    | '/studio/journal'
    | '/studio/licencing'
    | '/studio/manifesto'
    | '/studio/moodboard'
    | '/studio/morning-room'
    | '/studio/portfolio'
    | '/studio/positioning'
    | '/studio/seasonal-weather'
    | '/studio/soft-room'
    | '/studio/unlock-more'
    | '/studio/vintage-notes'
    | '/studio/why-seasonal'
    | '/studio/work-with-me'
  id:
    | '__root__'
    | '/'
    | '/begin-the-journey'
    | '/explore'
    | '/seasonal-house'
    | '/api/weather'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/products/$productId'
    | '/studio/about'
    | '/studio/another-room'
    | '/studio/collections'
    | '/studio/demo'
    | '/studio/depth-levels'
    | '/studio/evening-lounge'
    | '/studio/garden'
    | '/studio/homeware'
    | '/studio/interiors'
    | '/studio/journal'
    | '/studio/licencing'
    | '/studio/manifesto'
    | '/studio/moodboard'
    | '/studio/morning-room'
    | '/studio/portfolio'
    | '/studio/positioning'
    | '/studio/seasonal-weather'
    | '/studio/soft-room'
    | '/studio/unlock-more'
    | '/studio/vintage-notes'
    | '/studio/why-seasonal'
    | '/studio/work-with-me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeginTheJourneyRoute: typeof BeginTheJourneyRoute
  ExploreRoute: typeof ExploreRoute
  SeasonalHouseRoute: typeof SeasonalHouseRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  StudioAboutRoute: typeof StudioAboutRoute
  StudioAnotherRoomRoute: typeof StudioAnotherRoomRoute
  StudioCollectionsRoute: typeof StudioCollectionsRoute
  StudioDemoRoute: typeof StudioDemoRoute
  StudioDepthLevelsRoute: typeof StudioDepthLevelsRoute
  StudioEveningLoungeRoute: typeof StudioEveningLoungeRoute
  StudioGardenRoute: typeof StudioGardenRoute
  StudioHomewareRoute: typeof StudioHomewareRoute
  StudioInteriorsRoute: typeof StudioInteriorsRoute
  StudioJournalRoute: typeof StudioJournalRoute
  StudioLicencingRoute: typeof StudioLicencingRoute
  StudioManifestoRoute: typeof StudioManifestoRoute
  StudioMoodboardRoute: typeof StudioMoodboardRoute
  StudioMorningRoomRoute: typeof StudioMorningRoomRoute
  StudioPortfolioRoute: typeof StudioPortfolioRoute
  StudioPositioningRoute: typeof StudioPositioningRoute
  StudioSeasonalWeatherRoute: typeof StudioSeasonalWeatherRoute
  StudioSoftRoomRoute: typeof StudioSoftRoomRoute
  StudioUnlockMoreRoute: typeof StudioUnlockMoreRoute
  StudioVintageNotesRoute: typeof StudioVintageNotesRoute
  StudioWhySeasonalRoute: typeof StudioWhySeasonalRoute
  StudioWorkWithMeRoute: typeof StudioWorkWithMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seasonal-house': {
      id: '/seasonal-house'
      path: '/seasonal-house'
      fullPath: '/seasonal-house'
      preLoaderRoute: typeof SeasonalHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begin-the-journey': {
      id: '/begin-the-journey'
      path: '/begin-the-journey'
      fullPath: '/begin-the-journey'
      preLoaderRoute: typeof BeginTheJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/work-with-me': {
      id: '/studio/work-with-me'
      path: '/studio/work-with-me'
      fullPath: '/studio/work-with-me'
      preLoaderRoute: typeof StudioWorkWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/why-seasonal': {
      id: '/studio/why-seasonal'
      path: '/studio/why-seasonal'
      fullPath: '/studio/why-seasonal'
      preLoaderRoute: typeof StudioWhySeasonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/vintage-notes': {
      id: '/studio/vintage-notes'
      path: '/studio/vintage-notes'
      fullPath: '/studio/vintage-notes'
      preLoaderRoute: typeof StudioVintageNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/unlock-more': {
      id: '/studio/unlock-more'
      path: '/studio/unlock-more'
      fullPath: '/studio/unlock-more'
      preLoaderRoute: typeof StudioUnlockMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/soft-room': {
      id: '/studio/soft-room'
      path: '/studio/soft-room'
      fullPath: '/studio/soft-room'
      preLoaderRoute: typeof StudioSoftRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/seasonal-weather': {
      id: '/studio/seasonal-weather'
      path: '/studio/seasonal-weather'
      fullPath: '/studio/seasonal-weather'
      preLoaderRoute: typeof StudioSeasonalWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/positioning': {
      id: '/studio/positioning'
      path: '/studio/positioning'
      fullPath: '/studio/positioning'
      preLoaderRoute: typeof StudioPositioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/portfolio': {
      id: '/studio/portfolio'
      path: '/studio/portfolio'
      fullPath: '/studio/portfolio'
      preLoaderRoute: typeof StudioPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/morning-room': {
      id: '/studio/morning-room'
      path: '/studio/morning-room'
      fullPath: '/studio/morning-room'
      preLoaderRoute: typeof StudioMorningRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/moodboard': {
      id: '/studio/moodboard'
      path: '/studio/moodboard'
      fullPath: '/studio/moodboard'
      preLoaderRoute: typeof StudioMoodboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/manifesto': {
      id: '/studio/manifesto'
      path: '/studio/manifesto'
      fullPath: '/studio/manifesto'
      preLoaderRoute: typeof StudioManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/licencing': {
      id: '/studio/licencing'
      path: '/studio/licencing'
      fullPath: '/studio/licencing'
      preLoaderRoute: typeof StudioLicencingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/journal': {
      id: '/studio/journal'
      path: '/studio/journal'
      fullPath: '/studio/journal'
      preLoaderRoute: typeof StudioJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/interiors': {
      id: '/studio/interiors'
      path: '/studio/interiors'
      fullPath: '/studio/interiors'
      preLoaderRoute: typeof StudioInteriorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/homeware': {
      id: '/studio/homeware'
      path: '/studio/homeware'
      fullPath: '/studio/homeware'
      preLoaderRoute: typeof StudioHomewareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/garden': {
      id: '/studio/garden'
      path: '/studio/garden'
      fullPath: '/studio/garden'
      preLoaderRoute: typeof StudioGardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/evening-lounge': {
      id: '/studio/evening-lounge'
      path: '/studio/evening-lounge'
      fullPath: '/studio/evening-lounge'
      preLoaderRoute: typeof StudioEveningLoungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/depth-levels': {
      id: '/studio/depth-levels'
      path: '/studio/depth-levels'
      fullPath: '/studio/depth-levels'
      preLoaderRoute: typeof StudioDepthLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/demo': {
      id: '/studio/demo'
      path: '/studio/demo'
      fullPath: '/studio/demo'
      preLoaderRoute: typeof StudioDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/collections': {
      id: '/studio/collections'
      path: '/studio/collections'
      fullPath: '/studio/collections'
      preLoaderRoute: typeof StudioCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/another-room': {
      id: '/studio/another-room'
      path: '/studio/another-room'
      fullPath: '/studio/another-room'
      preLoaderRoute: typeof StudioAnotherRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/about': {
      id: '/studio/about'
      path: '/studio/about'
      fullPath: '/studio/about'
      preLoaderRoute: typeof StudioAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeginTheJourneyRoute: BeginTheJourneyRoute,
  ExploreRoute: ExploreRoute,
  SeasonalHouseRoute: SeasonalHouseRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  StudioAboutRoute: StudioAboutRoute,
  StudioAnotherRoomRoute: StudioAnotherRoomRoute,
  StudioCollectionsRoute: StudioCollectionsRoute,
  StudioDemoRoute: StudioDemoRoute,
  StudioDepthLevelsRoute: StudioDepthLevelsRoute,
  StudioEveningLoungeRoute: StudioEveningLoungeRoute,
  StudioGardenRoute: StudioGardenRoute,
  StudioHomewareRoute: StudioHomewareRoute,
  StudioInteriorsRoute: StudioInteriorsRoute,
  StudioJournalRoute: StudioJournalRoute,
  StudioLicencingRoute: StudioLicencingRoute,
  StudioManifestoRoute: StudioManifestoRoute,
  StudioMoodboardRoute: StudioMoodboardRoute,
  StudioMorningRoomRoute: StudioMorningRoomRoute,
  StudioPortfolioRoute: StudioPortfolioRoute,
  StudioPositioningRoute: StudioPositioningRoute,
  StudioSeasonalWeatherRoute: StudioSeasonalWeatherRoute,
  StudioSoftRoomRoute: StudioSoftRoomRoute,
  StudioUnlockMoreRoute: StudioUnlockMoreRoute,
  StudioVintageNotesRoute: StudioVintageNotesRoute,
  StudioWhySeasonalRoute: StudioWhySeasonalRoute,
  StudioWorkWithMeRoute: StudioWorkWithMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
