/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeasonalHouseRouteImport } from './routes/seasonal-house'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BeginTheJourneyRouteImport } from './routes/begin-the-journey'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioWorkWithMeRouteImport } from './routes/studio/work-with-me'
import { Route as StudioWhySeasonalRouteImport } from './routes/studio/why-seasonal'
import { Route as StudioPositioningRouteImport } from './routes/studio/positioning'
import { Route as StudioManifestoRouteImport } from './routes/studio/manifesto'
import { Route as StudioInteriorsRouteImport } from './routes/studio/interiors'
import { Route as StudioDepthLevelsRouteImport } from './routes/studio/depth-levels'
import { Route as StudioAboutRouteImport } from './routes/studio/about'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'

const SeasonalHouseRoute = SeasonalHouseRouteImport.update({
  id: '/seasonal-house',
  path: '/seasonal-house',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginTheJourneyRoute = BeginTheJourneyRouteImport.update({
  id: '/begin-the-journey',
  path: '/begin-the-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioWorkWithMeRoute = StudioWorkWithMeRouteImport.update({
  id: '/studio/work-with-me',
  path: '/studio/work-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioWhySeasonalRoute = StudioWhySeasonalRouteImport.update({
  id: '/studio/why-seasonal',
  path: '/studio/why-seasonal',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPositioningRoute = StudioPositioningRouteImport.update({
  id: '/studio/positioning',
  path: '/studio/positioning',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioManifestoRoute = StudioManifestoRouteImport.update({
  id: '/studio/manifesto',
  path: '/studio/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioInteriorsRoute = StudioInteriorsRouteImport.update({
  id: '/studio/interiors',
  path: '/studio/interiors',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioDepthLevelsRoute = StudioDepthLevelsRouteImport.update({
  id: '/studio/depth-levels',
  path: '/studio/depth-levels',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAboutRoute = StudioAboutRouteImport.update({
  id: '/studio/about',
  path: '/studio/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/begin-the-journey': typeof BeginTheJourneyRoute
  '/explore': typeof ExploreRoute
  '/seasonal-house': typeof SeasonalHouseRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/studio/about': typeof StudioAboutRoute
  '/studio/depth-levels': typeof StudioDepthLevelsRoute
  '/studio/interiors': typeof StudioInteriorsRoute
  '/studio/manifesto': typeof StudioManifestoRoute
  '/studio/positioning': typeof StudioPositioningRoute
  '/studio/why-seasonal': typeof StudioWhySeasonalRoute
  '/studio/work-with-me': typeof StudioWorkWithMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/begin-the-journey': typeof BeginTheJourneyRoute
  '/explore': typeof ExploreRoute
  '/seasonal-house': typeof SeasonalHouseRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/studio/about': typeof StudioAboutRoute
  '/studio/depth-levels': typeof StudioDepthLevelsRoute
  '/studio/interiors': typeof StudioInteriorsRoute
  '/studio/manifesto': typeof StudioManifestoRoute
  '/studio/positioning': typeof StudioPositioningRoute
  '/studio/why-seasonal': typeof StudioWhySeasonalRoute
  '/studio/work-with-me': typeof StudioWorkWithMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/begin-the-journey': typeof BeginTheJourneyRoute
  '/explore': typeof ExploreRoute
  '/seasonal-house': typeof SeasonalHouseRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/studio/about': typeof StudioAboutRoute
  '/studio/depth-levels': typeof StudioDepthLevelsRoute
  '/studio/interiors': typeof StudioInteriorsRoute
  '/studio/manifesto': typeof StudioManifestoRoute
  '/studio/positioning': typeof StudioPositioningRoute
  '/studio/why-seasonal': typeof StudioWhySeasonalRoute
  '/studio/work-with-me': typeof StudioWorkWithMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/begin-the-journey'
    | '/explore'
    | '/seasonal-house'
    | '/products/$productId'
    | '/studio/about'
    | '/studio/depth-levels'
    | '/studio/interiors'
    | '/studio/manifesto'
    | '/studio/positioning'
    | '/studio/why-seasonal'
    | '/studio/work-with-me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/begin-the-journey'
    | '/explore'
    | '/seasonal-house'
    | '/products/$productId'
    | '/studio/about'
    | '/studio/depth-levels'
    | '/studio/interiors'
    | '/studio/manifesto'
    | '/studio/positioning'
    | '/studio/why-seasonal'
    | '/studio/work-with-me'
  id:
    | '__root__'
    | '/'
    | '/begin-the-journey'
    | '/explore'
    | '/seasonal-house'
    | '/products/$productId'
    | '/studio/about'
    | '/studio/depth-levels'
    | '/studio/interiors'
    | '/studio/manifesto'
    | '/studio/positioning'
    | '/studio/why-seasonal'
    | '/studio/work-with-me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeginTheJourneyRoute: typeof BeginTheJourneyRoute
  ExploreRoute: typeof ExploreRoute
  SeasonalHouseRoute: typeof SeasonalHouseRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  StudioAboutRoute: typeof StudioAboutRoute
  StudioDepthLevelsRoute: typeof StudioDepthLevelsRoute
  StudioInteriorsRoute: typeof StudioInteriorsRoute
  StudioManifestoRoute: typeof StudioManifestoRoute
  StudioPositioningRoute: typeof StudioPositioningRoute
  StudioWhySeasonalRoute: typeof StudioWhySeasonalRoute
  StudioWorkWithMeRoute: typeof StudioWorkWithMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seasonal-house': {
      id: '/seasonal-house'
      path: '/seasonal-house'
      fullPath: '/seasonal-house'
      preLoaderRoute: typeof SeasonalHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begin-the-journey': {
      id: '/begin-the-journey'
      path: '/begin-the-journey'
      fullPath: '/begin-the-journey'
      preLoaderRoute: typeof BeginTheJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/work-with-me': {
      id: '/studio/work-with-me'
      path: '/studio/work-with-me'
      fullPath: '/studio/work-with-me'
      preLoaderRoute: typeof StudioWorkWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/why-seasonal': {
      id: '/studio/why-seasonal'
      path: '/studio/why-seasonal'
      fullPath: '/studio/why-seasonal'
      preLoaderRoute: typeof StudioWhySeasonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/positioning': {
      id: '/studio/positioning'
      path: '/studio/positioning'
      fullPath: '/studio/positioning'
      preLoaderRoute: typeof StudioPositioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/manifesto': {
      id: '/studio/manifesto'
      path: '/studio/manifesto'
      fullPath: '/studio/manifesto'
      preLoaderRoute: typeof StudioManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/interiors': {
      id: '/studio/interiors'
      path: '/studio/interiors'
      fullPath: '/studio/interiors'
      preLoaderRoute: typeof StudioInteriorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/depth-levels': {
      id: '/studio/depth-levels'
      path: '/studio/depth-levels'
      fullPath: '/studio/depth-levels'
      preLoaderRoute: typeof StudioDepthLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/about': {
      id: '/studio/about'
      path: '/studio/about'
      fullPath: '/studio/about'
      preLoaderRoute: typeof StudioAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeginTheJourneyRoute: BeginTheJourneyRoute,
  ExploreRoute: ExploreRoute,
  SeasonalHouseRoute: SeasonalHouseRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  StudioAboutRoute: StudioAboutRoute,
  StudioDepthLevelsRoute: StudioDepthLevelsRoute,
  StudioInteriorsRoute: StudioInteriorsRoute,
  StudioManifestoRoute: StudioManifestoRoute,
  StudioPositioningRoute: StudioPositioningRoute,
  StudioWhySeasonalRoute: StudioWhySeasonalRoute,
  StudioWorkWithMeRoute: StudioWorkWithMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
